theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/headphones
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.prune
    - search.suggest
    - navigation.top
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: purple
      accent: deep purple

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: purple
      accent: indigo
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
site_name: Sony Headphones Bluetooth Documentation
extra:
  generator: false
repo_url: https://github.com/ohm-app/sony-headphones-bluetooth-documentation
plugins: 
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_datetime
  - search
